### ISSUE TITLE
Small (possible) revision

### ISSUE THREAD

**Issue by Kwayzaar** [learn-co-curriculum/git-pushing-code-phase-0#1]
Not sure if this is revision-worthy but in the section "Set the Destination of a Repo with <git remote>", I think it would be helpful for new students if you added "your-repository-name" to the end of the command <my_new_directory $ git remote add origin>, so they know they are supposed to paste their repo's SSH URL there. 

It is stated in the "Conclusion" but it think it would be helpful in the previous section as well. 

Thanks for reading my contribution!

**Comment by maxwellbenton** [comment]
hey @Kwayzaar,

Thank you for catching this! This was due to an issue rendering GitHub markdown in Canvas - the repository had this included, but it wasn't appearing in Canvas. This should be fixed now for all students going forward. Thank you for taking the time to provide this feedback!

**Comment by Kwayzaar** [comment]
No worries! Thanks for looking into it!
