### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by erichegonzales** [learn-co-curriculum/git-pushing-code-phase-0#8]
### Canvas Link

https://learning.flatironschool.com/courses/5729/pages/pushing-code-with-git?module_item_id=395787

### Concern

Note: the workflow you've been using for labs also pushes code for you! When you run learn test, the learn-co gem automatically creates an fis-wip branch, saves the changes you've made to that branch, and pushes it up to your copy of the repo on GitHub. Once you have all the tests passing, the lab is registered as complete on Canvas and you have a backup of your code saved on GitHub.

### Suggested Changes

I recommend to include this note in the beginning of the course. I manually pushed each of my labs onto GitHub without realizing it was automatic 😅

**Comment by lizbur10** [comment]
Hi @erichegonzales - thanks for bringing this to our attention! I have clarified that point in the prework lesson, Complete Your First Software Engineering Assignment.

Thanks for helping us improve the Flatiron School curriculum 💙
